### ISSUE TITLE
Incompatibility with FastCraft+ 

### ISSUE THREAD

**Issue by 1434967947** [ericpauley/MagicChest#5]
THIS bug isn't fixed
[10:17:49 ERROR]: Could not pass event InventoryOpenEvent to MagicChest v1.2.7r1
org.bukkit.event.EventException
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:750) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.EntityPlayer.openContainer(EntityPlayer.java:728) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at org.bukkit.craftbukkit.v1_10_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:192) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at co.kepler.fastcraftplus.api.gui.GUI.show(GUI.java:88) [FastCraftPlus.jar:?]
	at co.kepler.fastcraftplus.craftgui.GUIFastCraft.show(GUIFastCraft.java:65) [FastCraftPlus.jar:?]
	at co.kepler.fastcraftplus.craftgui.GUIFastCraft.show(GUIFastCraft.java:72) [FastCraftPlus.jar:?]
	at co.kepler.fastcraftplus.craftgui.PlayerManager.onPlayerInteract(PlayerManager.java:47) [FastCraftPlus.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor85.execute(Unknown Source) [?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:492) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:893) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:796) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched.jar:git-TacoSpigot-"d9d17b4"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: co/kepler/fastcraftplus/api/gui/FastCraftAPI
	at org.zonedabone.magicchest.PluginCompatibility.isCompatibleInventory(PluginCompatibility.java:112) ~[?:?]
	at org.zonedabone.magicchest.Tools.SortInventory(Tools.java:28) ~[?:?]
	at org.zonedabone.magicchest.MagicChestListener.onInventoryOpen(MagicChestListener.java:26) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched.jar:git-TacoSpigot-"d9d17b4"]
	... 31 more
>

**Comment by uvbeenzaned** [comment]
This issue is a redundant post, there is already an issue with this title and we are still currently in the process of fixing and releasing MagicChest. I also will look at your stack trace in the mean time. Please post anything further in the already existing thread here: https://github.com/ericpauley/MagicChest/issues/4
